# Generated by Django 2.2.7 on 2019-11-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sookplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('detail_addr', models.TextField()),
                ('describe', models.TextField()),
            ],
        ),
    ]
