# Generated by Django 2.2.7 on 2019-11-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sookplaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sookplace',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sookplace/'),
        ),
    ]
