# Generated by Django 2.2.7 on 2019-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191116_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='describe',
        ),
    ]
