# Generated by Django 2.2.7 on 2019-11-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191129_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
