# Generated by Django 2.2.7 on 2019-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20191117_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', '소설'), ('society/culture', '사회/문화'), ('IT', 'IT')], max_length=10),
        ),
    ]
